// data.js
const properties = [
  {
    id: "1",
    slug: "villa-soho-dalmatia",
    title: "Villa Makarska",
    priceTag: "From €280 / daily",
    location: {
      area: "mountain",
      city: "Split",
      country: "italy",
    },
    pricePerNight: 620,
    currency: "EUR",
    capacity: {
      guests: 8,
      bedrooms: 8,
      bathrooms: 4,
    },
    gallery: ["/Assets/villas-image-1.png"],
    booking: { checkIn: "From 4:00 PM", checkOut: "Until 11:00 AM" },
    amenities: [
      "Swimming Pool",
      "WiFi",
      "Air Conditioning",
      "PlayStation",
      "Satellite TV",
      "Microwave",
      "Refrigerator",
      "Oven",
      "Coffee Machine",
      "Parking",
      "Gym",
      "Garden",
    ],
    agent: {
      name: "John Doe",
      phone: "+385 123 456 789",
      email: "villaagent@example.com",
    },
  },
  {
    id: "2",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Roxane",
    priceTag: "From €110 / daily",
    location: {
      area: "Seaside",
      city: "Lagos",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 11, bedrooms: 6, bathrooms: 25 },
    gallery: ["/Assets/villas-image-2.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "3",
    slug: "apartment-ikoyi-lagos",
    title: "Aphrodite",
    priceTag: "From €240 / daily",
    location: {
      area: "Seaside",
      city: "Lagos",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 12, bedrooms: 5, bathrooms: 5 },
    gallery: ["/Assets/villas-image-3.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },

  // {
  //   id: "4",
  //   slug: "apartment-ikoyi-lagos",
  //   title: "Luxury Apartment Ikoyi",
  //   priceTag: "From 280 / daily",
  //   location: {
  //     area: "Ikoyi",
  //     city: "Lagos",
  //     country: "Nigeria",
  //   },
  //   pricePerNight: 300,
  //   currency: "NGN",
  //   capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
  //   gallery: ["./Assets/Rectangle-4.png"],
  //   booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
  //   amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
  //   agent: {
  //     name: "Chinedu Okafor",
  //     phone: "+234 801 234 5678",
  //     email: "ikoyiagent@example.com",
  //   },
  // },
  // {
  //   id: "5",
  //   slug: "apartment-ikoyi-lagos",
  //   title: "Luxury Apartment Ikoyi",
  //   priceTag: "From 480 / daily",
  //   location: {
  //     area: "Ikoyi",
  //     city: "Lagos",
  //     country: "Nigeria",
  //   },
  //   pricePerNight: 300,
  //   currency: "NGN",
  //   capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
  //   gallery: ["./Assets/property-5.png"],
  //   booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
  //   amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
  //   agent: {
  //     name: "Chinedu Okafor",
  //     phone: "+234 801 234 5678",
  //     email: "ikoyiagent@example.com",
  //   },
  // },
  // {
  //   id: "6",
  //   slug: "apartment-ikoyi-lagos",
  //   title: "Luxury Apartment Ikoyi",
  //   priceTag: "From 780 / daily",
  //   location: {
  //     area: "Ikoyi",
  //     city: "Lagos",
  //     country: "Nigeria",
  //   },
  //   pricePerNight: 300,
  //   currency: "NGN",
  //   capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
  //   gallery: ["./Assets/propert-6.png"],
  //   booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
  //   amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
  //   agent: {
  //     name: "Chinedu Okafor",
  //     phone: "+234 801 234 5678",
  //     email: "ikoyiagent@example.com",
  //   },
  // },
  // {
  //   id: "7",
  //   slug: "apartment-ikoyi-lagos",
  //   title: "Luxury Apartment Ikoyi",
  //   priceTag: "From 300 / daily",
  //   location: {
  //     area: "Ikoyi",
  //     city: "Lagos",
  //     country: "Nigeria",
  //   },
  //   pricePerNight: 300,
  //   currency: "NGN",
  //   capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
  //   gallery: ["./Assets/property-7.png"],
  //   booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
  //   amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
  //   agent: {
  //     name: "Chinedu Okafor",
  //     phone: "+234 801 234 5678",
  //     email: "ikoyiagent@example.com",
  //   },
  // },
  // {
  //   id: "8",
  //   slug: "apartment-ikoyi-lagos",
  //   title: "Luxury Apartment Ikoyi",
  //   priceTag: "From 800 / daily",
  //   location: {
  //     area: "Ikoyi",
  //     city: "Lagos",
  //     country: "Nigeria",
  //   },
  //   pricePerNight: 300,
  //   currency: "NGN",
  //   capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
  //   gallery: ["./Assets/property-8.png"],
  //   booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
  //   amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
  //   agent: {
  //     name: "Chinedu Okafor",
  //     phone: "+234 801 234 5678",
  //     email: "ikoyiagent@example.com",
  //   },
  // },
  // {
  //   id: "9",
  //   slug: "apartment-ikoyi-lagos",
  //   title: "Luxury Apartment Ikoyi",
  //   priceTag: "From 780 / daily",
  //   location: {
  //     area: "Ikoyi",
  //     city: "Lagos",
  //     country: "Nigeria",
  //   },
  //   pricePerNight: 300,
  //   currency: "NGN",
  //   capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
  //   gallery: ["./Assets/property-9.png"],
  //   booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
  //   amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
  //   agent: {
  //     name: "Chinedu Okafor",
  //     phone: "+234 801 234 5678",
  //     email: "ikoyiagent@example.com",
  //   },
  // },
];